// eslint-disable-next-line @next/next/no-document-import-in-page
import { Head as NextHead } from 'next/document';

export default function Head() {
  return (
    <NextHead>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  );
}
